<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://validar.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://validar.com" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://validar.com">
			<xs:include schemaLocation="validar.xsd"/>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="validarMessagerequest">
    <wsdl:part name="parameter" element="tns:requestValidar">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="validarMessageresponse">
    <wsdl:part name="parameter" element="tns:responseValidar">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="validarPortType">
    <wsdl:operation name="validarOperation">
      <wsdl:input message="tns:validarMessagerequest">
    </wsdl:input>
      <wsdl:output message="tns:validarMessageresponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="validarBinding" type="tns:validarPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="validarOperation">
      <soap:operation soapAction="http://validar.com/validar"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="validar">
    <wsdl:port name="validarPort" binding="tns:validarBinding">
      <soap:address location="http://localhost:8080/axis2/services/validar"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
